# -*- coding: utf-8 -*-
"""Frontend Full Stack Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PxSLl1hnU6HTufSzUEq7UurRO9UZMl8n
"""

!pip install gradio requests transformers torch torchvision Pillow

import gradio as gr
from PIL import Image
import requests

# Replace with your Render API URL after deployment
API_URL = "https://your-render-api-url/caption"

def generate_caption(image):
    image.save("temp.jpg")
    files = {"file": open("temp.jpg", "rb")}
    response = requests.post(API_URL, files=files)
    return response.json()["caption"]

iface = gr.Interface(
    fn=generate_caption,
    inputs=gr.Image(type="pil"),
    outputs="text",
    title="Image Captioning AI - Fullstack",
    description="Upload an image, caption is generated via backend API."
)

iface.launch()
